apiVersion: v1
kind: Service
metadata:
  name: redis-service
  lebals:
    name: redis-service
    app: voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379    #default port for redis service
  selectors:
    name: redis-pod
    app: voting-app