apiVersion: v1
kind: Service
metadat: 
  name: voting-app-service
  labels:
    name: voting-app-service
    app: voting-app
  spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30004
    selector:
      name: voting-app-pod
      app: voting-app 